import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { 
  DiseasePredictionResult, 
  PrescriptionAnalysisResult, 
  MedicalImageAnalysisResult, 
  LiveCameraAnalysisResult 
} from '@/src/types/health';

export function generateDiseasePDF(result: DiseasePredictionResult, userName: string = 'User') {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(16, 185, 129); // emerald-500
  doc.setFontSize(22);
  doc.text("HEALTH.AI - EXPLAINABLE DIAGNOSIS REPORT", 14, 22);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text(`Patient: ${userName} | Generated: ${new Date().toLocaleString()}`, 14, 32);

  // Health Score & Primary Diagnosis
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(16);
  doc.text("Differential Diagnosis Overview", 14, 52);

  autoTable(doc, {
    startY: 56,
    head: [['Condition', 'Probability', 'Risk Level', 'Confidence', 'Severity']],
    body: (result.topDiseases || []).map(d => [
      d.disease,
      `${d.probability}%`,
      d.risk,
      `${d.confidence}%`,
      d.severity
    ]),
    headStyles: { fillColor: [15, 23, 42] },
    theme: 'grid'
  });

  let currentY = (doc as any).lastAutoTable.finalY + 12;

  // Clinical Reasoning
  doc.setFontSize(14);
  doc.text("Explainable AI Reasoning Summary", 14, currentY);
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const splitReasoning = doc.splitTextToSize(result.reasoningSummary || result.overview || '', pageWidth - 28);
  doc.text(splitReasoning, 14, currentY + 6);
  currentY += 8 + (splitReasoning.length * 5) + 8;

  // Symptom Contributions
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("Symptom Contributions", 14, currentY);

  autoTable(doc, {
    startY: currentY + 4,
    head: [['Symptom', 'Clinical Contribution', 'Importance Weight']],
    body: (result.contributingSymptoms || []).map(s => [
      s.symptom,
      s.contribution,
      `${s.importanceScore}/100`
    ]),
    headStyles: { fillColor: [51, 65, 85] },
    theme: 'striped'
  });
  currentY = (doc as any).lastAutoTable.finalY + 12;

  // Personalized Guidance
  if (currentY + 50 > doc.internal.pageSize.getHeight()) {
    doc.addPage();
    currentY = 20;
  }

  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("Personalized Care & Lifestyle Plan", 14, currentY);

  autoTable(doc, {
    startY: currentY + 4,
    head: [['Category', 'Recommendations']],
    body: [
      ['Lifestyle Advice', (result.lifestyleSuggestions || []).join(' • ')],
      ['Dietary Foods to Include', (result.dietRecommendations?.foodsToInclude || []).join(', ')],
      ['Foods to Limit', (result.dietRecommendations?.foodsToLimit || []).join(', ')],
      ['Exercise Routine', (result.exerciseRecommendations?.activities || []).join(', ')],
      ['Follow-up Action', result.followUpAdvice?.routineCheckup || 'Consult primary physician']
    ],
    headStyles: { fillColor: [16, 185, 129] },
    theme: 'grid'
  });

  // Footer Disclaimer
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(
    "DISCLAIMER: This document is generated by HEALTH.AI for educational and decision-support purposes. It is not a binding clinical diagnosis.",
    14,
    doc.internal.pageSize.getHeight() - 10
  );

  doc.save(`Health_AI_Diagnosis_${result.primaryDisease.replace(/\s+/g, '_')}.pdf`);
}

export function generatePrescriptionPDF(result: PrescriptionAnalysisResult, userName: string = 'User') {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header Banner
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(59, 130, 246); // blue-500
  doc.setFontSize(22);
  doc.text("HEALTH.AI - PRESCRIPTION OCR REPORT", 14, 22);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text(`Patient: ${userName} | Clinic: ${result.clinicName || 'N/A'} | Doctor: ${result.doctorName || 'N/A'}`, 14, 32);

  // Medicine Table
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(16);
  doc.text("Recognized Medications & Dosage Instructions", 14, 52);

  autoTable(doc, {
    startY: 56,
    head: [['Medication Name', 'Generic Active Ingredient', 'Purpose', 'Dosage', 'Timing', 'Food Relation']],
    body: (result.medicines || []).map(m => [
      m.name,
      m.genericName || 'N/A',
      m.purpose,
      m.dosage,
      m.timing,
      m.relationToFood
    ]),
    headStyles: { fillColor: [37, 99, 235] },
    theme: 'grid'
  });

  let currentY = (doc as any).lastAutoTable.finalY + 12;

  // Extracted Text
  doc.setFontSize(14);
  doc.text("Extracted OCR Transcript", 14, currentY);
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  const splitText = doc.splitTextToSize(result.extractedText || 'No raw text extracted', pageWidth - 28);
  doc.text(splitText.slice(0, 15), 14, currentY + 6);
  currentY += 8 + (Math.min(splitText.length, 15) * 4) + 10;

  // Unreadable & Warnings
  if (result.unreadableSections && result.unreadableSections.length > 0) {
    doc.setTextColor(220, 38, 38);
    doc.setFontSize(11);
    doc.text(`Unclear Handwriting Flags: ${result.unreadableSections.join('; ')}`, 14, currentY);
  }

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("ALWAYS VERIFY DOSAGES WITH YOUR PHARMACIST OR PRESCRIBING DOCTOR BEFORE MEDICATION USE.", 14, doc.internal.pageSize.getHeight() - 10);

  doc.save(`Health_AI_Prescription_OCR_${result.id.slice(0, 6)}.pdf`);
}

export function generateMedicalImagePDF(result: MedicalImageAnalysisResult, userName: string = 'User') {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(147, 51, 234); // purple-600
  doc.setFontSize(22);
  doc.text("HEALTH.AI - MEDICAL IMAGE ANALYSIS", 14, 22);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text(`Patient: ${userName} | Modality: ${result.imageType} | Quality Score: ${result.qualityCheck?.qualityScore || 90}/100`, 14, 32);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.text("Primary Clinical Interpretation", 14, 52);
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const splitInterp = doc.splitTextToSize(result.primaryInterpretation || result.plainLanguageExplanation || '', pageWidth - 28);
  doc.text(splitInterp, 14, 58);

  let currentY = 60 + (splitInterp.length * 5) + 10;

  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text("Possible Correlated Conditions", 14, currentY);

  autoTable(doc, {
    startY: currentY + 4,
    head: [['Condition', 'Relative AI Confidence', 'Description']],
    body: (result.possibleConditions || []).map(c => [
      c.condition,
      `${c.relativeConfidence}%`,
      c.description
    ]),
    headStyles: { fillColor: [147, 51, 234] },
    theme: 'grid'
  });

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("FOR EDUCATIONAL SCREENING ASSISTANCE ONLY. NOT A REPLACEMENT FOR FORMAL RADIOLOGIC REPORT.", 14, doc.internal.pageSize.getHeight() - 10);

  doc.save(`Health_AI_MedicalImage_${result.imageType.replace(/\s+/g, '_')}.pdf`);
}

export function generateLiveScanPDF(result: LiveCameraAnalysisResult, userName: string = 'User') {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(236, 72, 153); // pink-500
  doc.setFontSize(22);
  doc.text("HEALTH.AI - LIVE CAMERA ANALYSIS", 14, 22);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text(`Patient: ${userName} | Category: ${result.conditionCategory} | Confidence: ${result.confidenceLevel}`, 14, 32);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.text("Educational Analysis & Findings", 14, 52);
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const splitExp = doc.splitTextToSize(result.educationalExplanation || '', pageWidth - 28);
  doc.text(splitExp, 14, 58);

  let currentY = 60 + (splitExp.length * 5) + 10;

  autoTable(doc, {
    startY: currentY,
    head: [['Condition Pattern', 'Relative AI Match', 'Overview']],
    body: (result.possibleConditions || []).map(c => [
      c.condition,
      `${c.relativeConfidence}%`,
      c.overview
    ]),
    headStyles: { fillColor: [236, 72, 153] },
    theme: 'grid'
  });

  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text("EDUCATIONAL CAMERA SCREENING TOOL ONLY. SEE DERMATOLOGIST OR DOCTOR FOR CLINICAL CARE.", 14, doc.internal.pageSize.getHeight() - 10);

  doc.save(`Health_AI_LiveScan_${result.conditionCategory.replace(/\s+/g, '_')}.pdf`);
}
