import React, { useState } from 'react';
import { 
  Settings, ShieldAlert, Lock, LogOut, Save, RefreshCw, 
  FileText, Brain, Sliders, ToggleLeft, ToggleRight, CheckCircle2 
} from 'lucide-react';
import { cn } from '@/src/lib/utils';

interface SecuritySettingsTabProps {
  onAuditLog: (action: string, details: string) => void;
}

export default function SecuritySettingsTab({ onAuditLog }: SecuritySettingsTabProps) {
  const [maintenanceMode, setMaintenanceMode] = useState(false);
  const [sessionTimeoutMinutes, setSessionTimeoutMinutes] = useState(60);
  const [maxUploadSizeMb, setMaxUploadSizeMb] = useState(25);
  const [pdfWatermark, setPdfWatermark] = useState('HEALTH.AI OFFICIAL DIAGNOSTIC REPORT');
  const [pdfFooter, setPdfFooter] = useState('Confidential Patient Document • Generated by HEALTH.AI Engine');

  const handleSaveSettings = (e: React.FormEvent) => {
    e.preventDefault();
    onAuditLog('UPDATE_PLATFORM_SETTINGS', `Updated platform config: Maintenance=${maintenanceMode}, SessionTimeout=${sessionTimeoutMinutes}m, MaxUpload=${maxUploadSizeMb}MB`);
    alert('Platform settings saved and applied system-wide!');
  };

  const handleForceLogoutAll = () => {
    if (confirm('Are you sure you want to terminate ALL active user sessions platform-wide? Users will need to log in again.')) {
      onAuditLog('FORCE_LOGOUT_ALL_USERS', 'Terminated all active user sessions across the platform');
      alert('All active user sessions have been terminated.');
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-300">
      
      {/* Header */}
      <div className="rounded-3xl bg-slate-900 border border-white/10 p-6 shadow-2xl flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-2xl font-black text-white tracking-tight font-display">Platform Settings & Security Center</h2>
            <span className="px-2.5 py-0.5 rounded-full bg-slate-800 text-slate-300 font-bold text-[10px] uppercase tracking-widest">
              System Configuration
            </span>
          </div>
          <p className="text-slate-400 text-xs mt-1">
            Configure global maintenance mode, session timeout policies, PDF report watermarks, and security controls.
          </p>
        </div>

        <button
          onClick={handleForceLogoutAll}
          className="px-4 py-2.5 rounded-xl bg-rose-500/10 hover:bg-rose-500/20 text-rose-400 border border-rose-500/30 font-bold text-xs uppercase tracking-wider flex items-center gap-2"
        >
          <LogOut className="w-4 h-4" /> Force Logout All Users
        </button>
      </div>

      <form onSubmit={handleSaveSettings} className="space-y-8">
        
        {/* MAINTENANCE & SYSTEM CONTROLS */}
        <div className="rounded-3xl bg-slate-900 border border-white/10 p-6 shadow-2xl space-y-6">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <Settings className="w-4 h-4 text-cyan-400" /> Maintenance & Session Policy
          </h3>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            
            {/* Maintenance Mode */}
            <div className="p-4 rounded-2xl bg-slate-950 border border-white/5 space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-white">Maintenance Mode</span>
                <button
                  type="button"
                  onClick={() => setMaintenanceMode(!maintenanceMode)}
                  className="text-cyan-400"
                >
                  {maintenanceMode ? <ToggleRight className="w-8 h-8 text-rose-500" /> : <ToggleLeft className="w-8 h-8 text-slate-600" />}
                </button>
              </div>
              <p className="text-[11px] text-slate-400">
                When active, non-administrator users will see a maintenance screen.
              </p>
            </div>

            {/* Session Timeout */}
            <div className="p-4 rounded-2xl bg-slate-950 border border-white/5 space-y-2">
              <label className="text-xs font-bold text-white uppercase">Session Expiration (Minutes)</label>
              <input
                type="number"
                value={sessionTimeoutMinutes}
                onChange={(e) => setSessionTimeoutMinutes(Number(e.target.value))}
                className="w-full p-2.5 rounded-xl bg-slate-900 border border-white/10 text-white font-mono text-xs"
              />
              <p className="text-[10px] text-slate-500">Inactivity timeout before auto-logout</p>
            </div>

            {/* Max Upload Size */}
            <div className="p-4 rounded-2xl bg-slate-950 border border-white/5 space-y-2">
              <label className="text-xs font-bold text-white uppercase">Max File Upload Size (MB)</label>
              <input
                type="number"
                value={maxUploadSizeMb}
                onChange={(e) => setMaxUploadSizeMb(Number(e.target.value))}
                className="w-full p-2.5 rounded-xl bg-slate-900 border border-white/10 text-white font-mono text-xs"
              />
              <p className="text-[10px] text-slate-500">Max limit for radiology DICOM & prescription images</p>
            </div>

          </div>
        </div>

        {/* PDF REPORT BRANDING SETTINGS */}
        <div className="rounded-3xl bg-slate-900 border border-white/10 p-6 shadow-2xl space-y-4">
          <h3 className="text-sm font-bold text-white uppercase tracking-wider flex items-center gap-2">
            <FileText className="w-4 h-4 text-emerald-400" /> PDF Diagnostic Report Branding
          </h3>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 text-xs">
            <div>
              <label className="font-bold text-slate-300 uppercase">PDF Watermark Text</label>
              <input
                type="text"
                value={pdfWatermark}
                onChange={(e) => setPdfWatermark(e.target.value)}
                className="w-full mt-1 p-3 rounded-xl bg-slate-950 border border-white/10 text-white font-mono"
              />
            </div>

            <div>
              <label className="font-bold text-slate-300 uppercase">PDF Footer Legal Notice</label>
              <input
                type="text"
                value={pdfFooter}
                onChange={(e) => setPdfFooter(e.target.value)}
                className="w-full mt-1 p-3 rounded-xl bg-slate-950 border border-white/10 text-white font-mono"
              />
            </div>
          </div>
        </div>

        {/* SAVE BUTTON */}
        <div className="flex justify-end">
          <button
            type="submit"
            className="px-6 py-3 rounded-2xl bg-cyan-500 hover:bg-cyan-600 text-slate-950 font-black uppercase tracking-wider flex items-center gap-2 shadow-lg shadow-cyan-500/25 transition-all"
          >
            <Save className="w-4 h-4" /> Save System Settings
          </button>
        </div>

      </form>

    </div>
  );
}
